BEGIN TRY

BEGIN TRAN;

-- AlterTable
ALTER TABLE [dbo].[Task] ADD [isActive] BIT NOT NULL CONSTRAINT [Task_isActive_df] DEFAULT 1,
[isCompleted] BIT NOT NULL CONSTRAINT [Task_isCompleted_df] DEFAULT 0;

COMMIT TRAN;

END TRY
BEGIN CATCH

IF @@TRANCOUNT > 0
BEGIN
    ROLLBACK TRAN;
END;
THROW

END CATCH
